### ISSUE TITLE
Incorrect password crashes server

### ISSUE THREAD

**Issue by Ekeyes8500** [brijamfitz/project-2#6]
If the user enters a password that is not there, the entire server crashes.
Stack trace below: 

Unhandled rejection RangeError: Invalid status code: [object Object]
    at ServerResponse.writeHead (_http_server.js:194:11)
    at ServerResponse.writeHead (C:\repos\project-2\node_modules\on-headers\index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:185:8)
    at write_ (_http_outgoing.js:632:9)
    at ServerResponse.write (_http_outgoing.js:617:10)
    at writetop (C:\repos\project-2\node_modules\express-session\index.js:290:26)
    at ServerResponse.end (C:\repos\project-2\node_modules\express-session\index.js:351:16)
    at ServerResponse.redirect (C:\repos\project-2\node_modules\express\lib\response.js:947:10)
    at C:\repos\project-2\routes\apiRoutes.js:20:20
    at allFailed (C:\repos\project-2\node_modules\passport\lib\middleware\authenticate.js:107:18)
    at attempt (C:\repos\project-2\node_modules\passport\lib\middleware\authenticate.js:180:28)
    at Strategy.strategy.fail (C:\repos\project-2\node_modules\passport\lib\middleware\authenticate.js:297:9)
    at verified (C:\repos\project-2\node_modules\passport-local\lib\strategy.js:82:30)
    at C:\repos\project-2\config\passport.js:18:20
    at tryCatcher (C:\repos\project-2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\repos\project-2\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\repos\project-2\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\repos\project-2\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\repos\project-2\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\repos\project-2\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\repos\project-2\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\repos\project-2\node_modules\bluebird\js\release\async.js:147:5)

C:\repos\project-2\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^

RangeError: Invalid status code: [object Object]
    at ServerResponse.writeHead (_http_server.js:194:11)
    at ServerResponse.writeHead (C:\repos\project-2\node_modules\on-headers\index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:185:8)
    at write_ (_http_outgoing.js:632:9)
    at ServerResponse.end (_http_outgoing.js:751:5)
    at writeend (C:\repos\project-2\node_modules\express-session\index.js:261:22)
    at ontouch (C:\repos\project-2\node_modules\express-session\index.js:348:11)
    at tryCatcher (C:\repos\project-2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\repos\project-2\node_modules\bluebird\js\release\nodeify.js:23:30)
    at Promise._settlePromise (C:\repos\project-2\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\repos\project-2\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\repos\project-2\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\repos\project-2\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\repos\project-2\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\repos\project-2\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\repos\project-2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by harryby1149** [comment]
FIxed it, added error handling
